<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gtfs-realtime.proto

namespace Transit_realtime;

if (false) {
    /**
     * This class is deprecated. Use Transit_realtime\Alert\SeverityLevel instead.
     * @deprecated
     */
    class Alert_SeverityLevel {}
}
class_exists(Alert\SeverityLevel::class);
@trigger_error('Transit_realtime\Alert_SeverityLevel is deprecated and will be removed in the next major release. Use Transit_realtime\Alert\SeverityLevel instead', E_USER_DEPRECATED);

