<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gtfs-realtime.proto

namespace Transit_realtime;

if (false) {
    /**
     * This class is deprecated. Use Transit_realtime\Stop\WheelchairBoarding instead.
     * @deprecated
     */
    class Stop_WheelchairBoarding {}
}
class_exists(Stop\WheelchairBoarding::class);
@trigger_error('Transit_realtime\Stop_WheelchairBoarding is deprecated and will be removed in the next major release. Use Transit_realtime\Stop\WheelchairBoarding instead', E_USER_DEPRECATED);

