<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gtfs-realtime.proto

namespace Transit_realtime;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Describes a stop which is served by trips. All fields are as described in the GTFS-Static specification.
 * NOTE: This message is still experimental, and subject to change. It may be formally adopted in the future.
 *
 * Generated from protobuf message <code>transit_realtime.Stop</code>
 */
class Stop extends \Google\Protobuf\Internal\Message
{
    /**
     * optional string stop_id = 1;
     *
     * Generated from protobuf field <code>string stop_id = 1;</code>
     */
    protected $stop_id = '';
    /**
     * optional TranslatedString stop_code = 2;
     *
     * Generated from protobuf field <code>.transit_realtime.TranslatedString stop_code = 2;</code>
     */
    protected $stop_code = null;
    /**
     * optional TranslatedString stop_name = 3;
     *
     * Generated from protobuf field <code>.transit_realtime.TranslatedString stop_name = 3;</code>
     */
    protected $stop_name = null;
    /**
     * optional TranslatedString tts_stop_name = 4;
     *
     * Generated from protobuf field <code>.transit_realtime.TranslatedString tts_stop_name = 4;</code>
     */
    protected $tts_stop_name = null;
    /**
     * optional TranslatedString stop_desc = 5;
     *
     * Generated from protobuf field <code>.transit_realtime.TranslatedString stop_desc = 5;</code>
     */
    protected $stop_desc = null;
    /**
     * optional float stop_lat = 6;
     *
     * Generated from protobuf field <code>float stop_lat = 6;</code>
     */
    protected $stop_lat = 0.0;
    /**
     * optional float stop_lon = 7;
     *
     * Generated from protobuf field <code>float stop_lon = 7;</code>
     */
    protected $stop_lon = 0.0;
    /**
     * optional string zone_id = 8;
     *
     * Generated from protobuf field <code>string zone_id = 8;</code>
     */
    protected $zone_id = '';
    /**
     * optional TranslatedString stop_url = 9;
     *
     * Generated from protobuf field <code>.transit_realtime.TranslatedString stop_url = 9;</code>
     */
    protected $stop_url = null;
    /**
     * optional string parent_station = 11;
     *
     * Generated from protobuf field <code>string parent_station = 11;</code>
     */
    protected $parent_station = '';
    /**
     * optional string stop_timezone = 12;
     *
     * Generated from protobuf field <code>string stop_timezone = 12;</code>
     */
    protected $stop_timezone = '';
    /**
     * optional WheelchairBoarding wheelchair_boarding = 13 [default = UNKNOWN];
     *
     * Generated from protobuf field <code>.transit_realtime.Stop.WheelchairBoarding wheelchair_boarding = 13;</code>
     */
    protected $wheelchair_boarding = 0;
    /**
     * optional string level_id = 14;
     *
     * Generated from protobuf field <code>string level_id = 14;</code>
     */
    protected $level_id = '';
    /**
     * optional TranslatedString platform_code = 15;
     *
     * Generated from protobuf field <code>.transit_realtime.TranslatedString platform_code = 15;</code>
     */
    protected $platform_code = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $stop_id
     *           optional string stop_id = 1;
     *     @type \Transit_realtime\TranslatedString $stop_code
     *           optional TranslatedString stop_code = 2;
     *     @type \Transit_realtime\TranslatedString $stop_name
     *           optional TranslatedString stop_name = 3;
     *     @type \Transit_realtime\TranslatedString $tts_stop_name
     *           optional TranslatedString tts_stop_name = 4;
     *     @type \Transit_realtime\TranslatedString $stop_desc
     *           optional TranslatedString stop_desc = 5;
     *     @type float $stop_lat
     *           optional float stop_lat = 6;
     *     @type float $stop_lon
     *           optional float stop_lon = 7;
     *     @type string $zone_id
     *           optional string zone_id = 8;
     *     @type \Transit_realtime\TranslatedString $stop_url
     *           optional TranslatedString stop_url = 9;
     *     @type string $parent_station
     *           optional string parent_station = 11;
     *     @type string $stop_timezone
     *           optional string stop_timezone = 12;
     *     @type int $wheelchair_boarding
     *           optional WheelchairBoarding wheelchair_boarding = 13 [default = UNKNOWN];
     *     @type string $level_id
     *           optional string level_id = 14;
     *     @type \Transit_realtime\TranslatedString $platform_code
     *           optional TranslatedString platform_code = 15;
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\GtfsRealtime::initOnce();
        parent::__construct($data);
    }

    /**
     * optional string stop_id = 1;
     *
     * Generated from protobuf field <code>string stop_id = 1;</code>
     * @return string
     */
    public function getStopId()
    {
        return $this->stop_id;
    }

    /**
     * optional string stop_id = 1;
     *
     * Generated from protobuf field <code>string stop_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setStopId($var)
    {
        GPBUtil::checkString($var, True);
        $this->stop_id = $var;

        return $this;
    }

    /**
     * optional TranslatedString stop_code = 2;
     *
     * Generated from protobuf field <code>.transit_realtime.TranslatedString stop_code = 2;</code>
     * @return \Transit_realtime\TranslatedString|null
     */
    public function getStopCode()
    {
        return $this->stop_code;
    }

    public function hasStopCode()
    {
        return isset($this->stop_code);
    }

    public function clearStopCode()
    {
        unset($this->stop_code);
    }

    /**
     * optional TranslatedString stop_code = 2;
     *
     * Generated from protobuf field <code>.transit_realtime.TranslatedString stop_code = 2;</code>
     * @param \Transit_realtime\TranslatedString $var
     * @return $this
     */
    public function setStopCode($var)
    {
        GPBUtil::checkMessage($var, \Transit_realtime\TranslatedString::class);
        $this->stop_code = $var;

        return $this;
    }

    /**
     * optional TranslatedString stop_name = 3;
     *
     * Generated from protobuf field <code>.transit_realtime.TranslatedString stop_name = 3;</code>
     * @return \Transit_realtime\TranslatedString|null
     */
    public function getStopName()
    {
        return $this->stop_name;
    }

    public function hasStopName()
    {
        return isset($this->stop_name);
    }

    public function clearStopName()
    {
        unset($this->stop_name);
    }

    /**
     * optional TranslatedString stop_name = 3;
     *
     * Generated from protobuf field <code>.transit_realtime.TranslatedString stop_name = 3;</code>
     * @param \Transit_realtime\TranslatedString $var
     * @return $this
     */
    public function setStopName($var)
    {
        GPBUtil::checkMessage($var, \Transit_realtime\TranslatedString::class);
        $this->stop_name = $var;

        return $this;
    }

    /**
     * optional TranslatedString tts_stop_name = 4;
     *
     * Generated from protobuf field <code>.transit_realtime.TranslatedString tts_stop_name = 4;</code>
     * @return \Transit_realtime\TranslatedString|null
     */
    public function getTtsStopName()
    {
        return $this->tts_stop_name;
    }

    public function hasTtsStopName()
    {
        return isset($this->tts_stop_name);
    }

    public function clearTtsStopName()
    {
        unset($this->tts_stop_name);
    }

    /**
     * optional TranslatedString tts_stop_name = 4;
     *
     * Generated from protobuf field <code>.transit_realtime.TranslatedString tts_stop_name = 4;</code>
     * @param \Transit_realtime\TranslatedString $var
     * @return $this
     */
    public function setTtsStopName($var)
    {
        GPBUtil::checkMessage($var, \Transit_realtime\TranslatedString::class);
        $this->tts_stop_name = $var;

        return $this;
    }

    /**
     * optional TranslatedString stop_desc = 5;
     *
     * Generated from protobuf field <code>.transit_realtime.TranslatedString stop_desc = 5;</code>
     * @return \Transit_realtime\TranslatedString|null
     */
    public function getStopDesc()
    {
        return $this->stop_desc;
    }

    public function hasStopDesc()
    {
        return isset($this->stop_desc);
    }

    public function clearStopDesc()
    {
        unset($this->stop_desc);
    }

    /**
     * optional TranslatedString stop_desc = 5;
     *
     * Generated from protobuf field <code>.transit_realtime.TranslatedString stop_desc = 5;</code>
     * @param \Transit_realtime\TranslatedString $var
     * @return $this
     */
    public function setStopDesc($var)
    {
        GPBUtil::checkMessage($var, \Transit_realtime\TranslatedString::class);
        $this->stop_desc = $var;

        return $this;
    }

    /**
     * optional float stop_lat = 6;
     *
     * Generated from protobuf field <code>float stop_lat = 6;</code>
     * @return float
     */
    public function getStopLat()
    {
        return $this->stop_lat;
    }

    /**
     * optional float stop_lat = 6;
     *
     * Generated from protobuf field <code>float stop_lat = 6;</code>
     * @param float $var
     * @return $this
     */
    public function setStopLat($var)
    {
        GPBUtil::checkFloat($var);
        $this->stop_lat = $var;

        return $this;
    }

    /**
     * optional float stop_lon = 7;
     *
     * Generated from protobuf field <code>float stop_lon = 7;</code>
     * @return float
     */
    public function getStopLon()
    {
        return $this->stop_lon;
    }

    /**
     * optional float stop_lon = 7;
     *
     * Generated from protobuf field <code>float stop_lon = 7;</code>
     * @param float $var
     * @return $this
     */
    public function setStopLon($var)
    {
        GPBUtil::checkFloat($var);
        $this->stop_lon = $var;

        return $this;
    }

    /**
     * optional string zone_id = 8;
     *
     * Generated from protobuf field <code>string zone_id = 8;</code>
     * @return string
     */
    public function getZoneId()
    {
        return $this->zone_id;
    }

    /**
     * optional string zone_id = 8;
     *
     * Generated from protobuf field <code>string zone_id = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setZoneId($var)
    {
        GPBUtil::checkString($var, True);
        $this->zone_id = $var;

        return $this;
    }

    /**
     * optional TranslatedString stop_url = 9;
     *
     * Generated from protobuf field <code>.transit_realtime.TranslatedString stop_url = 9;</code>
     * @return \Transit_realtime\TranslatedString|null
     */
    public function getStopUrl()
    {
        return $this->stop_url;
    }

    public function hasStopUrl()
    {
        return isset($this->stop_url);
    }

    public function clearStopUrl()
    {
        unset($this->stop_url);
    }

    /**
     * optional TranslatedString stop_url = 9;
     *
     * Generated from protobuf field <code>.transit_realtime.TranslatedString stop_url = 9;</code>
     * @param \Transit_realtime\TranslatedString $var
     * @return $this
     */
    public function setStopUrl($var)
    {
        GPBUtil::checkMessage($var, \Transit_realtime\TranslatedString::class);
        $this->stop_url = $var;

        return $this;
    }

    /**
     * optional string parent_station = 11;
     *
     * Generated from protobuf field <code>string parent_station = 11;</code>
     * @return string
     */
    public function getParentStation()
    {
        return $this->parent_station;
    }

    /**
     * optional string parent_station = 11;
     *
     * Generated from protobuf field <code>string parent_station = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setParentStation($var)
    {
        GPBUtil::checkString($var, True);
        $this->parent_station = $var;

        return $this;
    }

    /**
     * optional string stop_timezone = 12;
     *
     * Generated from protobuf field <code>string stop_timezone = 12;</code>
     * @return string
     */
    public function getStopTimezone()
    {
        return $this->stop_timezone;
    }

    /**
     * optional string stop_timezone = 12;
     *
     * Generated from protobuf field <code>string stop_timezone = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setStopTimezone($var)
    {
        GPBUtil::checkString($var, True);
        $this->stop_timezone = $var;

        return $this;
    }

    /**
     * optional WheelchairBoarding wheelchair_boarding = 13 [default = UNKNOWN];
     *
     * Generated from protobuf field <code>.transit_realtime.Stop.WheelchairBoarding wheelchair_boarding = 13;</code>
     * @return int
     */
    public function getWheelchairBoarding()
    {
        return $this->wheelchair_boarding;
    }

    /**
     * optional WheelchairBoarding wheelchair_boarding = 13 [default = UNKNOWN];
     *
     * Generated from protobuf field <code>.transit_realtime.Stop.WheelchairBoarding wheelchair_boarding = 13;</code>
     * @param int $var
     * @return $this
     */
    public function setWheelchairBoarding($var)
    {
        GPBUtil::checkEnum($var, \Transit_realtime\Stop\WheelchairBoarding::class);
        $this->wheelchair_boarding = $var;

        return $this;
    }

    /**
     * optional string level_id = 14;
     *
     * Generated from protobuf field <code>string level_id = 14;</code>
     * @return string
     */
    public function getLevelId()
    {
        return $this->level_id;
    }

    /**
     * optional string level_id = 14;
     *
     * Generated from protobuf field <code>string level_id = 14;</code>
     * @param string $var
     * @return $this
     */
    public function setLevelId($var)
    {
        GPBUtil::checkString($var, True);
        $this->level_id = $var;

        return $this;
    }

    /**
     * optional TranslatedString platform_code = 15;
     *
     * Generated from protobuf field <code>.transit_realtime.TranslatedString platform_code = 15;</code>
     * @return \Transit_realtime\TranslatedString|null
     */
    public function getPlatformCode()
    {
        return $this->platform_code;
    }

    public function hasPlatformCode()
    {
        return isset($this->platform_code);
    }

    public function clearPlatformCode()
    {
        unset($this->platform_code);
    }

    /**
     * optional TranslatedString platform_code = 15;
     *
     * Generated from protobuf field <code>.transit_realtime.TranslatedString platform_code = 15;</code>
     * @param \Transit_realtime\TranslatedString $var
     * @return $this
     */
    public function setPlatformCode($var)
    {
        GPBUtil::checkMessage($var, \Transit_realtime\TranslatedString::class);
        $this->platform_code = $var;

        return $this;
    }

}

