<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gtfs-realtime.proto

namespace Transit_realtime;

if (false) {
    /**
     * This class is deprecated. Use Transit_realtime\TranslatedImage\LocalizedImage instead.
     * @deprecated
     */
    class TranslatedImage_LocalizedImage {}
}
class_exists(TranslatedImage\LocalizedImage::class);
@trigger_error('Transit_realtime\TranslatedImage_LocalizedImage is deprecated and will be removed in the next major release. Use Transit_realtime\TranslatedImage\LocalizedImage instead', E_USER_DEPRECATED);

