<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gtfs-realtime.proto

namespace Transit_realtime;

if (false) {
    /**
     * This class is deprecated. Use Transit_realtime\TripDescriptor\ModifiedTripSelector instead.
     * @deprecated
     */
    class TripDescriptor_ModifiedTripSelector {}
}
class_exists(TripDescriptor\ModifiedTripSelector::class);
@trigger_error('Transit_realtime\TripDescriptor_ModifiedTripSelector is deprecated and will be removed in the next major release. Use Transit_realtime\TripDescriptor\ModifiedTripSelector instead', E_USER_DEPRECATED);

