<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gtfs-realtime.proto

namespace Transit_realtime;

if (false) {
    /**
     * This class is deprecated. Use Transit_realtime\TripModifications\Modification instead.
     * @deprecated
     */
    class TripModifications_Modification {}
}
class_exists(TripModifications\Modification::class);
@trigger_error('Transit_realtime\TripModifications_Modification is deprecated and will be removed in the next major release. Use Transit_realtime\TripModifications\Modification instead', E_USER_DEPRECATED);

