<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gtfs-realtime.proto

namespace Transit_realtime;

if (false) {
    /**
     * This class is deprecated. Use Transit_realtime\TripUpdate\StopTimeUpdate\StopTimeProperties instead.
     * @deprecated
     */
    class TripUpdate_StopTimeUpdate_StopTimeProperties {}
}
class_exists(TripUpdate\StopTimeUpdate\StopTimeProperties::class);
@trigger_error('Transit_realtime\TripUpdate_StopTimeUpdate_StopTimeProperties is deprecated and will be removed in the next major release. Use Transit_realtime\TripUpdate\StopTimeUpdate\StopTimeProperties instead', E_USER_DEPRECATED);

