<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gtfs-realtime.proto

namespace Transit_realtime;

if (false) {
    /**
     * This class is deprecated. Use Transit_realtime\TripModifications\SelectedTrips instead.
     * @deprecated
     */
    class TripModifications_SelectedTrips {}
}
class_exists(TripModifications\SelectedTrips::class);
@trigger_error('Transit_realtime\TripModifications_SelectedTrips is deprecated and will be removed in the next major release. Use Transit_realtime\TripModifications\SelectedTrips instead', E_USER_DEPRECATED);

