<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gtfs-realtime.proto

namespace Transit_realtime;

if (false) {
    /**
     * This class is deprecated. Use Transit_realtime\TripUpdate\TripProperties instead.
     * @deprecated
     */
    class TripUpdate_TripProperties {}
}
class_exists(TripUpdate\TripProperties::class);
@trigger_error('Transit_realtime\TripUpdate_TripProperties is deprecated and will be removed in the next major release. Use Transit_realtime\TripUpdate\TripProperties instead', E_USER_DEPRECATED);

