<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gtfs-realtime.proto

namespace Transit_realtime;

if (false) {
    /**
     * This class is deprecated. Use Transit_realtime\VehiclePosition\CarriageDetails instead.
     * @deprecated
     */
    class VehiclePosition_CarriageDetails {}
}
class_exists(VehiclePosition\CarriageDetails::class);
@trigger_error('Transit_realtime\VehiclePosition_CarriageDetails is deprecated and will be removed in the next major release. Use Transit_realtime\VehiclePosition\CarriageDetails instead', E_USER_DEPRECATED);

