<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gtfs-realtime.proto

namespace Transit_realtime;

if (false) {
    /**
     * This class is deprecated. Use Transit_realtime\VehicleDescriptor\WheelchairAccessible instead.
     * @deprecated
     */
    class VehicleDescriptor_WheelchairAccessible {}
}
class_exists(VehicleDescriptor\WheelchairAccessible::class);
@trigger_error('Transit_realtime\VehicleDescriptor_WheelchairAccessible is deprecated and will be removed in the next major release. Use Transit_realtime\VehicleDescriptor\WheelchairAccessible instead', E_USER_DEPRECATED);

