<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gtfs-realtime.proto

namespace Google\Transit\Realtime\TripModifications;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * A `Modification` message replaces a span of n stop times from each affected trip starting at `start_stop_selector`.
 *
 * Generated from protobuf message <code>google.transit.realtime.TripModifications.Modification</code>
 */
class Modification extends \Google\Protobuf\Internal\Message
{
    /**
     * The stop selector of the first stop_time of the original trip that is to be affected by this modification.
     * Used in conjuction with `end_stop_selector`.
     * `start_stop_selector` is required and is used to define the reference stop used with `travel_time_to_stop`.
     * optional StopSelector start_stop_selector = 1;
     *
     * Generated from protobuf field <code>.google.transit.realtime.StopSelector start_stop_selector = 1;</code>
     */
    protected $start_stop_selector = null;
    /**
     * The stop selector of the last stop of the original trip that is to be affected by this modification.
     * The selection is inclusive, so if only one stop_time is replaced by that modification, `start_stop_selector` and `end_stop_selector` must be equivalent.
     * If no stop_time is replaced, `end_stop_selector` must not be provided. It's otherwise required.
     * optional StopSelector end_stop_selector = 2;
     *
     * Generated from protobuf field <code>.google.transit.realtime.StopSelector end_stop_selector = 2;</code>
     */
    protected $end_stop_selector = null;
    /**
     * The number of seconds of delay to add to all departure and arrival times following the end of this modification.
     * If multiple modifications apply to the same trip, the delays accumulate as the trip advances.
     * optional int32 propagated_modification_delay = 3 [default = 0];
     *
     * Generated from protobuf field <code>int32 propagated_modification_delay = 3;</code>
     */
    protected $propagated_modification_delay = 0;
    /**
     * A list of replacement stops, replacing those of the original trip.
     * The length of the new stop times may be less, the same, or greater than the number of replaced stop times.
     *
     * Generated from protobuf field <code>repeated .google.transit.realtime.ReplacementStop replacement_stops = 4;</code>
     */
    private $replacement_stops;
    /**
     * An `id` value from the `FeedEntity` message that contains the `Alert` describing this Modification for user-facing communication.
     * optional string service_alert_id = 5;
     *
     * Generated from protobuf field <code>string service_alert_id = 5;</code>
     */
    protected $service_alert_id = '';
    /**
     * This timestamp identifies the moment when the modification has last been changed.
     * In POSIX time (i.e., number of seconds since January 1st 1970 00:00:00 UTC).
     * optional uint64 last_modified_time = 6;
     *
     * Generated from protobuf field <code>uint64 last_modified_time = 6;</code>
     */
    protected $last_modified_time = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Transit\Realtime\StopSelector $start_stop_selector
     *           The stop selector of the first stop_time of the original trip that is to be affected by this modification.
     *           Used in conjuction with `end_stop_selector`.
     *           `start_stop_selector` is required and is used to define the reference stop used with `travel_time_to_stop`.
     *           optional StopSelector start_stop_selector = 1;
     *     @type \Google\Transit\Realtime\StopSelector $end_stop_selector
     *           The stop selector of the last stop of the original trip that is to be affected by this modification.
     *           The selection is inclusive, so if only one stop_time is replaced by that modification, `start_stop_selector` and `end_stop_selector` must be equivalent.
     *           If no stop_time is replaced, `end_stop_selector` must not be provided. It's otherwise required.
     *           optional StopSelector end_stop_selector = 2;
     *     @type int $propagated_modification_delay
     *           The number of seconds of delay to add to all departure and arrival times following the end of this modification.
     *           If multiple modifications apply to the same trip, the delays accumulate as the trip advances.
     *           optional int32 propagated_modification_delay = 3 [default = 0];
     *     @type array<\Google\Transit\Realtime\ReplacementStop>|\Google\Protobuf\Internal\RepeatedField $replacement_stops
     *           A list of replacement stops, replacing those of the original trip.
     *           The length of the new stop times may be less, the same, or greater than the number of replaced stop times.
     *     @type string $service_alert_id
     *           An `id` value from the `FeedEntity` message that contains the `Alert` describing this Modification for user-facing communication.
     *           optional string service_alert_id = 5;
     *     @type int|string $last_modified_time
     *           This timestamp identifies the moment when the modification has last been changed.
     *           In POSIX time (i.e., number of seconds since January 1st 1970 00:00:00 UTC).
     *           optional uint64 last_modified_time = 6;
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Transit\Realtime\GtfsRealtime::initOnce();
        parent::__construct($data);
    }

    /**
     * The stop selector of the first stop_time of the original trip that is to be affected by this modification.
     * Used in conjuction with `end_stop_selector`.
     * `start_stop_selector` is required and is used to define the reference stop used with `travel_time_to_stop`.
     * optional StopSelector start_stop_selector = 1;
     *
     * Generated from protobuf field <code>.google.transit.realtime.StopSelector start_stop_selector = 1;</code>
     * @return \Google\Transit\Realtime\StopSelector|null
     */
    public function getStartStopSelector()
    {
        return $this->start_stop_selector;
    }

    public function hasStartStopSelector()
    {
        return isset($this->start_stop_selector);
    }

    public function clearStartStopSelector()
    {
        unset($this->start_stop_selector);
    }

    /**
     * The stop selector of the first stop_time of the original trip that is to be affected by this modification.
     * Used in conjuction with `end_stop_selector`.
     * `start_stop_selector` is required and is used to define the reference stop used with `travel_time_to_stop`.
     * optional StopSelector start_stop_selector = 1;
     *
     * Generated from protobuf field <code>.google.transit.realtime.StopSelector start_stop_selector = 1;</code>
     * @param \Google\Transit\Realtime\StopSelector $var
     * @return $this
     */
    public function setStartStopSelector($var)
    {
        GPBUtil::checkMessage($var, \Google\Transit\Realtime\StopSelector::class);
        $this->start_stop_selector = $var;

        return $this;
    }

    /**
     * The stop selector of the last stop of the original trip that is to be affected by this modification.
     * The selection is inclusive, so if only one stop_time is replaced by that modification, `start_stop_selector` and `end_stop_selector` must be equivalent.
     * If no stop_time is replaced, `end_stop_selector` must not be provided. It's otherwise required.
     * optional StopSelector end_stop_selector = 2;
     *
     * Generated from protobuf field <code>.google.transit.realtime.StopSelector end_stop_selector = 2;</code>
     * @return \Google\Transit\Realtime\StopSelector|null
     */
    public function getEndStopSelector()
    {
        return $this->end_stop_selector;
    }

    public function hasEndStopSelector()
    {
        return isset($this->end_stop_selector);
    }

    public function clearEndStopSelector()
    {
        unset($this->end_stop_selector);
    }

    /**
     * The stop selector of the last stop of the original trip that is to be affected by this modification.
     * The selection is inclusive, so if only one stop_time is replaced by that modification, `start_stop_selector` and `end_stop_selector` must be equivalent.
     * If no stop_time is replaced, `end_stop_selector` must not be provided. It's otherwise required.
     * optional StopSelector end_stop_selector = 2;
     *
     * Generated from protobuf field <code>.google.transit.realtime.StopSelector end_stop_selector = 2;</code>
     * @param \Google\Transit\Realtime\StopSelector $var
     * @return $this
     */
    public function setEndStopSelector($var)
    {
        GPBUtil::checkMessage($var, \Google\Transit\Realtime\StopSelector::class);
        $this->end_stop_selector = $var;

        return $this;
    }

    /**
     * The number of seconds of delay to add to all departure and arrival times following the end of this modification.
     * If multiple modifications apply to the same trip, the delays accumulate as the trip advances.
     * optional int32 propagated_modification_delay = 3 [default = 0];
     *
     * Generated from protobuf field <code>int32 propagated_modification_delay = 3;</code>
     * @return int
     */
    public function getPropagatedModificationDelay()
    {
        return $this->propagated_modification_delay;
    }

    /**
     * The number of seconds of delay to add to all departure and arrival times following the end of this modification.
     * If multiple modifications apply to the same trip, the delays accumulate as the trip advances.
     * optional int32 propagated_modification_delay = 3 [default = 0];
     *
     * Generated from protobuf field <code>int32 propagated_modification_delay = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setPropagatedModificationDelay($var)
    {
        GPBUtil::checkInt32($var);
        $this->propagated_modification_delay = $var;

        return $this;
    }

    /**
     * A list of replacement stops, replacing those of the original trip.
     * The length of the new stop times may be less, the same, or greater than the number of replaced stop times.
     *
     * Generated from protobuf field <code>repeated .google.transit.realtime.ReplacementStop replacement_stops = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getReplacementStops()
    {
        return $this->replacement_stops;
    }

    /**
     * A list of replacement stops, replacing those of the original trip.
     * The length of the new stop times may be less, the same, or greater than the number of replaced stop times.
     *
     * Generated from protobuf field <code>repeated .google.transit.realtime.ReplacementStop replacement_stops = 4;</code>
     * @param array<\Google\Transit\Realtime\ReplacementStop>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setReplacementStops($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Transit\Realtime\ReplacementStop::class);
        $this->replacement_stops = $arr;

        return $this;
    }

    /**
     * An `id` value from the `FeedEntity` message that contains the `Alert` describing this Modification for user-facing communication.
     * optional string service_alert_id = 5;
     *
     * Generated from protobuf field <code>string service_alert_id = 5;</code>
     * @return string
     */
    public function getServiceAlertId()
    {
        return $this->service_alert_id;
    }

    /**
     * An `id` value from the `FeedEntity` message that contains the `Alert` describing this Modification for user-facing communication.
     * optional string service_alert_id = 5;
     *
     * Generated from protobuf field <code>string service_alert_id = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setServiceAlertId($var)
    {
        GPBUtil::checkString($var, True);
        $this->service_alert_id = $var;

        return $this;
    }

    /**
     * This timestamp identifies the moment when the modification has last been changed.
     * In POSIX time (i.e., number of seconds since January 1st 1970 00:00:00 UTC).
     * optional uint64 last_modified_time = 6;
     *
     * Generated from protobuf field <code>uint64 last_modified_time = 6;</code>
     * @return int|string
     */
    public function getLastModifiedTime()
    {
        return $this->last_modified_time;
    }

    /**
     * This timestamp identifies the moment when the modification has last been changed.
     * In POSIX time (i.e., number of seconds since January 1st 1970 00:00:00 UTC).
     * optional uint64 last_modified_time = 6;
     *
     * Generated from protobuf field <code>uint64 last_modified_time = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLastModifiedTime($var)
    {
        GPBUtil::checkUint64($var);
        $this->last_modified_time = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Modification::class, \Google\Transit\Realtime\TripModifications_Modification::class);

