<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gtfs-realtime.proto

namespace Google\Transit\Realtime;

if (false) {
    /**
     * This class is deprecated. Use Google\Transit\Realtime\Stop\WheelchairBoarding instead.
     * @deprecated
     */
    class Stop_WheelchairBoarding {}
}
class_exists(Stop\WheelchairBoarding::class);
@trigger_error('Google\Transit\Realtime\Stop_WheelchairBoarding is deprecated and will be removed in the next major release. Use Google\Transit\Realtime\Stop\WheelchairBoarding instead', E_USER_DEPRECATED);

