<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gtfs-realtime.proto

namespace Google\Transit\Realtime;

if (false) {
    /**
     * This class is deprecated. Use Google\Transit\Realtime\TripModifications\SelectedTrips instead.
     * @deprecated
     */
    class TripModifications_SelectedTrips {}
}
class_exists(TripModifications\SelectedTrips::class);
@trigger_error('Google\Transit\Realtime\TripModifications_SelectedTrips is deprecated and will be removed in the next major release. Use Google\Transit\Realtime\TripModifications\SelectedTrips instead', E_USER_DEPRECATED);

