<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gtfs-realtime.proto

namespace Google\Transit\Realtime;

if (false) {
    /**
     * This class is deprecated. Use Google\Transit\Realtime\TripDescriptor\ModifiedTripSelector instead.
     * @deprecated
     */
    class TripDescriptor_ModifiedTripSelector {}
}
class_exists(TripDescriptor\ModifiedTripSelector::class);
@trigger_error('Google\Transit\Realtime\TripDescriptor_ModifiedTripSelector is deprecated and will be removed in the next major release. Use Google\Transit\Realtime\TripDescriptor\ModifiedTripSelector instead', E_USER_DEPRECATED);

