<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gtfs-realtime.proto

namespace Google\Transit\Realtime;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * NOTE: This field is still experimental, and subject to change. It may be formally adopted in the future.
 *
 * Generated from protobuf message <code>google.transit.realtime.TripModifications</code>
 */
class TripModifications extends \Google\Protobuf\Internal\Message
{
    /**
     * A list of selected trips affected by this TripModifications.
     *
     * Generated from protobuf field <code>repeated .google.transit.realtime.TripModifications.SelectedTrips selected_trips = 1;</code>
     */
    private $selected_trips;
    /**
     * A list of start times in the real-time trip descriptor for the trip_id defined in trip_ids.
     * Useful to target multiple departures of a trip_id in a frequency-based trip.
     *
     * Generated from protobuf field <code>repeated string start_times = 2;</code>
     */
    private $start_times;
    /**
     * Dates on which the modifications occurs, in the YYYYMMDD format. Producers SHOULD only transmit detours occurring within the next week.
     * The dates provided should not be used as user-facing information, if a user-facing start and end date needs to be provided, they can be provided in the linked service alert with `service_alert_id`
     *
     * Generated from protobuf field <code>repeated string service_dates = 3;</code>
     */
    private $service_dates;
    /**
     * A list of modifications to apply to the affected trips.
     *
     * Generated from protobuf field <code>repeated .google.transit.realtime.TripModifications.Modification modifications = 4;</code>
     */
    private $modifications;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Google\Transit\Realtime\TripModifications\SelectedTrips>|\Google\Protobuf\Internal\RepeatedField $selected_trips
     *           A list of selected trips affected by this TripModifications.
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $start_times
     *           A list of start times in the real-time trip descriptor for the trip_id defined in trip_ids.
     *           Useful to target multiple departures of a trip_id in a frequency-based trip.
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $service_dates
     *           Dates on which the modifications occurs, in the YYYYMMDD format. Producers SHOULD only transmit detours occurring within the next week.
     *           The dates provided should not be used as user-facing information, if a user-facing start and end date needs to be provided, they can be provided in the linked service alert with `service_alert_id`
     *     @type array<\Google\Transit\Realtime\TripModifications\Modification>|\Google\Protobuf\Internal\RepeatedField $modifications
     *           A list of modifications to apply to the affected trips.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Transit\Realtime\GtfsRealtime::initOnce();
        parent::__construct($data);
    }

    /**
     * A list of selected trips affected by this TripModifications.
     *
     * Generated from protobuf field <code>repeated .google.transit.realtime.TripModifications.SelectedTrips selected_trips = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSelectedTrips()
    {
        return $this->selected_trips;
    }

    /**
     * A list of selected trips affected by this TripModifications.
     *
     * Generated from protobuf field <code>repeated .google.transit.realtime.TripModifications.SelectedTrips selected_trips = 1;</code>
     * @param array<\Google\Transit\Realtime\TripModifications\SelectedTrips>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSelectedTrips($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Transit\Realtime\TripModifications\SelectedTrips::class);
        $this->selected_trips = $arr;

        return $this;
    }

    /**
     * A list of start times in the real-time trip descriptor for the trip_id defined in trip_ids.
     * Useful to target multiple departures of a trip_id in a frequency-based trip.
     *
     * Generated from protobuf field <code>repeated string start_times = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getStartTimes()
    {
        return $this->start_times;
    }

    /**
     * A list of start times in the real-time trip descriptor for the trip_id defined in trip_ids.
     * Useful to target multiple departures of a trip_id in a frequency-based trip.
     *
     * Generated from protobuf field <code>repeated string start_times = 2;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setStartTimes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->start_times = $arr;

        return $this;
    }

    /**
     * Dates on which the modifications occurs, in the YYYYMMDD format. Producers SHOULD only transmit detours occurring within the next week.
     * The dates provided should not be used as user-facing information, if a user-facing start and end date needs to be provided, they can be provided in the linked service alert with `service_alert_id`
     *
     * Generated from protobuf field <code>repeated string service_dates = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getServiceDates()
    {
        return $this->service_dates;
    }

    /**
     * Dates on which the modifications occurs, in the YYYYMMDD format. Producers SHOULD only transmit detours occurring within the next week.
     * The dates provided should not be used as user-facing information, if a user-facing start and end date needs to be provided, they can be provided in the linked service alert with `service_alert_id`
     *
     * Generated from protobuf field <code>repeated string service_dates = 3;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setServiceDates($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->service_dates = $arr;

        return $this;
    }

    /**
     * A list of modifications to apply to the affected trips.
     *
     * Generated from protobuf field <code>repeated .google.transit.realtime.TripModifications.Modification modifications = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getModifications()
    {
        return $this->modifications;
    }

    /**
     * A list of modifications to apply to the affected trips.
     *
     * Generated from protobuf field <code>repeated .google.transit.realtime.TripModifications.Modification modifications = 4;</code>
     * @param array<\Google\Transit\Realtime\TripModifications\Modification>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setModifications($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Transit\Realtime\TripModifications\Modification::class);
        $this->modifications = $arr;

        return $this;
    }

}

