<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gtfs-realtime.proto

namespace Google\Transit\Realtime;

if (false) {
    /**
     * This class is deprecated. Use Google\Transit\Realtime\TripModifications\Modification instead.
     * @deprecated
     */
    class TripModifications_Modification {}
}
class_exists(TripModifications\Modification::class);
@trigger_error('Google\Transit\Realtime\TripModifications_Modification is deprecated and will be removed in the next major release. Use Google\Transit\Realtime\TripModifications\Modification instead', E_USER_DEPRECATED);

