<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gtfs-realtime.proto

namespace Transit_realtime\Stop;

use UnexpectedValueException;

/**
 * Protobuf type <code>transit_realtime.Stop.WheelchairBoarding</code>
 */
class WheelchairBoarding
{
    /**
     * Generated from protobuf enum <code>UNKNOWN = 0;</code>
     */
    const UNKNOWN = 0;
    /**
     * Generated from protobuf enum <code>AVAILABLE = 1;</code>
     */
    const AVAILABLE = 1;
    /**
     * Generated from protobuf enum <code>NOT_AVAILABLE = 2;</code>
     */
    const NOT_AVAILABLE = 2;

    private static $valueToName = [
        self::UNKNOWN => 'UNKNOWN',
        self::AVAILABLE => 'AVAILABLE',
        self::NOT_AVAILABLE => 'NOT_AVAILABLE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(WheelchairBoarding::class, \Transit_realtime\Stop_WheelchairBoarding::class);

