<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gtfs-realtime.proto

namespace Google\Transit\Realtime\TripDescriptor;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>google.transit.realtime.TripDescriptor.ModifiedTripSelector</code>
 */
class ModifiedTripSelector extends \Google\Protobuf\Internal\Message
{
    /**
     * The 'id' from the FeedEntity in which the contained TripModifications object affects this trip.
     * optional string modifications_id = 1;
     *
     * Generated from protobuf field <code>string modifications_id = 1;</code>
     */
    protected $modifications_id = '';
    /**
     * The trip_id from the GTFS feed that is modified by the modifications_id
     * optional string affected_trip_id = 2;
     *
     * Generated from protobuf field <code>string affected_trip_id = 2;</code>
     */
    protected $affected_trip_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $modifications_id
     *           The 'id' from the FeedEntity in which the contained TripModifications object affects this trip.
     *           optional string modifications_id = 1;
     *     @type string $affected_trip_id
     *           The trip_id from the GTFS feed that is modified by the modifications_id
     *           optional string affected_trip_id = 2;
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\GtfsRealtime::initOnce();
        parent::__construct($data);
    }

    /**
     * The 'id' from the FeedEntity in which the contained TripModifications object affects this trip.
     * optional string modifications_id = 1;
     *
     * Generated from protobuf field <code>string modifications_id = 1;</code>
     * @return string
     */
    public function getModificationsId()
    {
        return $this->modifications_id;
    }

    /**
     * The 'id' from the FeedEntity in which the contained TripModifications object affects this trip.
     * optional string modifications_id = 1;
     *
     * Generated from protobuf field <code>string modifications_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setModificationsId($var)
    {
        GPBUtil::checkString($var, True);
        $this->modifications_id = $var;

        return $this;
    }

    /**
     * The trip_id from the GTFS feed that is modified by the modifications_id
     * optional string affected_trip_id = 2;
     *
     * Generated from protobuf field <code>string affected_trip_id = 2;</code>
     * @return string
     */
    public function getAffectedTripId()
    {
        return $this->affected_trip_id;
    }

    /**
     * The trip_id from the GTFS feed that is modified by the modifications_id
     * optional string affected_trip_id = 2;
     *
     * Generated from protobuf field <code>string affected_trip_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setAffectedTripId($var)
    {
        GPBUtil::checkString($var, True);
        $this->affected_trip_id = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(ModifiedTripSelector::class, \Google\Transit\Realtime\TripDescriptor_ModifiedTripSelector::class);

