<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gtfs-realtime.proto

namespace Transit_realtime\TripModifications;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>transit_realtime.TripModifications.SelectedTrips</code>
 */
class SelectedTrips extends \Google\Protobuf\Internal\Message
{
    /**
     * A list of trips affected with this replacement that all have the same new `shape_id`.
     *
     * Generated from protobuf field <code>repeated string trip_ids = 1;</code>
     */
    private $trip_ids;
    /**
     * The ID of the new shape for the modified trips in this SelectedTrips.
     * May refer to a new shape added using a GTFS-RT Shape message, or to an existing shape defined in the GTFS-Static feed’s shapes.txt.
     * optional string shape_id = 2;
     *
     * Generated from protobuf field <code>string shape_id = 2;</code>
     */
    protected $shape_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $trip_ids
     *           A list of trips affected with this replacement that all have the same new `shape_id`.
     *     @type string $shape_id
     *           The ID of the new shape for the modified trips in this SelectedTrips.
     *           May refer to a new shape added using a GTFS-RT Shape message, or to an existing shape defined in the GTFS-Static feed’s shapes.txt.
     *           optional string shape_id = 2;
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\GtfsRealtime::initOnce();
        parent::__construct($data);
    }

    /**
     * A list of trips affected with this replacement that all have the same new `shape_id`.
     *
     * Generated from protobuf field <code>repeated string trip_ids = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTripIds()
    {
        return $this->trip_ids;
    }

    /**
     * A list of trips affected with this replacement that all have the same new `shape_id`.
     *
     * Generated from protobuf field <code>repeated string trip_ids = 1;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTripIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->trip_ids = $arr;

        return $this;
    }

    /**
     * The ID of the new shape for the modified trips in this SelectedTrips.
     * May refer to a new shape added using a GTFS-RT Shape message, or to an existing shape defined in the GTFS-Static feed’s shapes.txt.
     * optional string shape_id = 2;
     *
     * Generated from protobuf field <code>string shape_id = 2;</code>
     * @return string
     */
    public function getShapeId()
    {
        return $this->shape_id;
    }

    /**
     * The ID of the new shape for the modified trips in this SelectedTrips.
     * May refer to a new shape added using a GTFS-RT Shape message, or to an existing shape defined in the GTFS-Static feed’s shapes.txt.
     * optional string shape_id = 2;
     *
     * Generated from protobuf field <code>string shape_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setShapeId($var)
    {
        GPBUtil::checkString($var, True);
        $this->shape_id = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(SelectedTrips::class, \Transit_realtime\TripModifications_SelectedTrips::class);

